name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Archive 
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'magento-getnet.zip'
        exclusions: '*.git* LICENSE README.md'
    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        artifacts: "magento-getnet.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
